line-length = 100
select = [
  # "ALL",
  "B007",
  "B904",
  "C901",
  "D415",
  "D400",
  "E501",
  "E712",
  "F401",
  "F541",
  "F821",
  "F841",
  "G004",
  "I001",
  "T201",
  "N802",
  "N806",
  "Q000",
  "W291",
  "W292",
  "W293",
  "ANN001",
  "ANN201",
  "ERA001",
  "COM812",
  "SIM102",
  "SIM117",
  "RET503",
  "RET505",
  "TRY401",
  "PLR0402",
  "PLR5501",
]
# ignore = ["E203"]  # Игнорировать определенные правила
